[theme]
primaryColor = "#7CB342"          # verde principal (botones, sliders, etc.)
backgroundColor = "#0B1116"       # fondo de la app
secondaryBackgroundColor = "#141A1F"  # fondo de tarjetas / sidebar
textColor = "#FFFFFF"             # color del texto
font = "sans serif"               # fuente b√°sica

