[theme]
primaryColor = "#DFEFDA"              # Verde suave, botones / sliders
backgroundColor = "#F8F5EE"           # Fondo claro tipo beige
secondaryBackgroundColor = "#656D4A"  # Fondo de contenedores / cards
textColor = "#000000"                 # Texto oscuro natural
font = "sans serif"
