[theme]
primaryColor = "#92C184"          # verde principal (botones, sliders, etc.)
backgroundColor = "#0B1116"       # fondo de la app
secondaryBackgroundColor = "#656D4A"  # fondo de tarjetas / sidebar
textColor = "#FFFFFF"             # color del texto
font = "sans serif"               # fuente b√°sica

