[theme]
primaryColor = "#A4AC86"              # Verde suave, botones / sliders
backgroundColor = "#F8F5EE"           # Fondo claro tipo beige
secondaryBackgroundColor = "#C2C5AA"  # Fondo de contenedores / cards
textColor = "#ffffff"                 # Texto oscuro natural
font = "sans serif"
